from .access import (
    count_six_and_find_eight,
    first_last_and_at_2,
    nums_reversed_builtin,
    nums_reversed_method,
    nums_reversed_slice,
    slices_2_to_6_and_negative,
    split_at_4,
)
from .add import add_items, concat_with_extend, concat_with_plus
from .change import change_items
from .comprehension import double_elements, evens_from_range, filter_greater_than, square_elements
from .copy_lists import (
    copy_with_copy,
    copy_with_deepcopy,
    copy_with_list,
    copy_with_slice,
    deep_first_level_append,
    deep_first_level_pop,
    deep_nested_append,
    shallow_first_level_append,
    shallow_first_level_pop,
    shallow_nested_append,
)
from .loop import (
    collect_by_index,
    collect_direct,
    collect_reversed,
    collect_reversed_by_index,
    collect_reversed_slice,
    collect_while_step,
)
from .remove import remove_all_occurrences, remove_all_occurrences_in_place, remove_items
from .sort import (
    reversed_new_list,
    reverse_items,
    sort_ascending,
    sort_by_abs,
    sort_by_distance_from_12,
    sort_by_int,
    sort_by_len,
    sort_by_str,
    sort_by_str_lower,
    sort_by_str_strip,
    sort_descending,
)

__all__ = [
    "count_six_and_find_eight",
    "first_last_and_at_2",
    "nums_reversed_builtin",
    "nums_reversed_method",
    "nums_reversed_slice",
    "slices_2_to_6_and_negative",
    "split_at_4",
    "add_items",
    "concat_with_extend",
    "concat_with_plus",
    "change_items",
    "double_elements",
    "evens_from_range",
    "filter_greater_than",
    "square_elements",
    "copy_with_copy",
    "copy_with_deepcopy",
    "copy_with_list",
    "copy_with_slice",
    "deep_first_level_append",
    "deep_first_level_pop",
    "deep_nested_append",
    "shallow_first_level_append",
    "shallow_first_level_pop",
    "shallow_nested_append",
    "collect_by_index",
    "collect_direct",
    "collect_reversed",
    "collect_reversed_by_index",
    "collect_reversed_slice",
    "collect_while_step",
    "remove_all_occurrences",
    "remove_all_occurrences_in_place",
    "remove_items",
    "reversed_new_list",
    "reverse_items",
    "sort_ascending",
    "sort_by_abs",
    "sort_by_distance_from_12",
    "sort_by_int",
    "sort_by_len",
    "sort_by_str",
    "sort_by_str_lower",
    "sort_by_str_strip",
    "sort_descending",
]
