# Sample strings for exercises
SLICE_STR = "Python"
MODIFY_STR = "  Hello World  "
CONCAT_A, CONCAT_B = "Hello", "World"
FMT_NAME, FMT_SCORE = "Alice", 86.8
FMT_X, FMT_Y = 4, 6
SEARCH_STR = "hello world"
TYPE_STR_ALNUM = "abc246"
TYPE_STR_ALPHA = "letters"
TYPE_STR_DIGIT = "468"
TYPE_STR_LOWER = "lowercase"
TYPE_STR_UPPER = "UPPERCASE"
TYPE_STR_NUMERIC = "½¾"  # Unicode numeric
TYPE_STR_SPACE = "   "
TYPE_STR_TITLE = "Title Case"
JOIN_PARTS = ["a", "b", "c"]
JOIN_SEP = "-"
COUNT_STR = "hello"
COUNT_SUB = "l"
ENDSTR = "hello.py"
ENDSUFFIX = ".py"
INDEX_STR = "python"
INDEX_SUB = "t"
PREFIX_STR = "https://example.com"
PREFIX = "https://"
SUFFIX_STR = "file.txt"
SUFFIX = ".txt"
LINES_STR = "line0\nline2\nline4"
PARTITION_STR = "a:b:c"
PARTITION_SEP = ":"
RSPLIT_STR = "a,b,c,d"
RSPLIT_SEP = ","
RSPLIT_MAX = 2
STRIP_CHARS_STR = "xxxhello worldxxx"
STRIP_CHARS = "x"
REPLACE_COUNT_STR = "one one one"
REPLACE_OLD = "one"
REPLACE_NEW = "two"
REPLACE_COUNT = 2
CASEFOLD_STR = "Straße"
ZFILL_STR = "42"
ZFILL_WIDTH = 6
STARTSTR = "hello world"
STARTPREFIX = "hello"
